// constants/offerLetterVariables.ts

export const OFFER_LETTER_VARIABLES = [
  "companyLogoUrl",
  "companyName",
  "companyAddress",
  "companyEmail",
  "companyPhone",
  "todayDate",
  "candidateFirstName",
  "candidateFullName",
  "jobTitle",
  "salaryNumeric",
  "salaryWords",
  "startDate",
  "workLocation",
  "teamName",
  "managerName",
  "managerTitle",
  "offerExpiryDate",
  "hrName",
  "hrTitle",
  "salary.basic",
  "salary.hra",
  "salary.allowances",
  "salary.pension",
  "salary.total",
  "payDay",
  "paymentMethod",
  "probationPeriod",
  "revisionAfter",
  "insuranceCoverage",
  "sig_cand",
  "date_cand",
  "sig_emp",
  "date_emp",
] as const;
